### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by dgtlkvn** [kasparsd/metrogram#2]
Hello, I don't know if you are still supporting this. But all of a sudden I am getting an error loading this. I am getting "Cannot read property 'length' of undefined". Did something change with the instagram API?

Thanks,
Kevin

**Comment by ghost** [comment]
Hello,
i have the same problem: "Cannot read property 'length' of undefined".
Are there news?

Thanks,
Jacopo

**Comment by kasparsd** [comment]
@Dinacea Looks like you need to update the access token. I'm seeing the same error message:

```
The access_token provided is invalid.
```
